version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    
  broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  
  transaction_loader:
    build: 
      context: transaction_loader
      dockerfile: Dockerfile_transaction_loader
    container_name :  transaction_loader
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8501:8501"
    restart: "no"
    volumes:
        - ./data/:/transaction_loader/data
        - ./transaction_loader/:/transaction_loader
    environment:
      KFK: 101
      kafka_source_topic: transactions
      kafka_source_groupid: transactions
      kafka_server_name: broker
      kafka_server_port: 29092
      kafka_linger_ms: 200
      kafka_partitioner: murmur2_random
  predictionapi:
    build: 
      context: predictionapi
      dockerfile: Dockerfile_predictionsvc
    container_name: predictionapi
    ports:
      - '5000:5000'
    restart: "no"
    volumes:
        - ./models/model.sav:/predictionapi/model.sav
        - ./models/type.pkl:/predictionapi/type.pkl
        - ./models/beneficiary.pkl:/predictionapi/beneficiary.pkl
        - ./models/country.pkl:/predictionapi/country.pkl
        - ./predictionapi/:/predictionapi
