FROM python:3.7
#FROM python:3.7-alpine
EXPOSE 8501
WORKDIR /transaction_loader
COPY ./ /transaction_loader
WORKDIR /transaction_loader
RUN pip3 install -r requirements.txt
CMD ["streamlit", "run","app.py"]
